---
- name: making cache
  yum:
    update_cache: yes

- name: updating package
  yum:
    name: '*'
    state: latest

- name: installing bind-utils
  yum:
    name: bind-utils
    state: latest

- name: checking if chrony installed
  stat:
    path: /bin/chronyc
  register: chrony_check

- name: Debug Chrony check result
  debug:
    msg: "Chrony check result: {{ chrony_check }}"

- name: installing chrony
  yum:
    name: chrony
    state: latest
  when: not chrony_check.stat.exists

- name: configuring /etc/chrony.conf
  template:
    src: chronytemplate.j2
    dest: /etc/chrony.conf
    backup: yes

- name: restart chrony, if its installed
  service:
    name: chronyd
    state: restarted
  when: chrony_check.stat.exists

- name: starting and enabling chronyd
  service:
    name: chronyd
    state: started
    enabled: yes
  when: not chrony_check.stat.exists

- name: getting uuid of network
  command: nmcli -g uuid con show
  register: uuid_result

- name: configuring IP address
  template:
    src: ipconfig.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3
    backup: yes

- name: getting a hostname
  command: hostname
  register: current_hostname

- name: setting a hostname
  hostname:
    name: ntp-server-50.ziyotek.local
  when: current_hostname.stdout != "ntp-server-50.ziyotek.local"

- name: setting firewall rules for ntp
  firewalld:
    service: ntp
    permanent: yes
    immediate: yes
    state: enabled

- name: setting firewall rules for dns
  firewalld:
    service: dns
    permanent: yes
    immediate: yes
    state: enabled

- name: reloading firewalld
  service:
    name: firewalld
    state: reloaded

- name: creating a user "adam"
  user:
    name: adam
    state: present
    create_home: yes

- name: adding "adam" to sudoers file
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^adam'
    line: 'adam ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: restarting network
  service:
    name: network
    state: restarted